on:
  push:
    branches:
      - "sonarscan"
    paths:
      - ".github/workflows/sonar.yml"
 
name: SonarQube
env:
  SONAR_PROJECTKEY: $GITHUB_REPOSITORY
jobs:
  sonarQubeTrigger:
    name: SonarQube Scan
    runs-on: [self-hosted, sonar]
    steps:
    - uses: actions/checkout@v3
    - name: create property file
      run: |
        echo "sonar.host.url=${{ secrets.SONAR_URL }}" >> sonar-project.properties
        echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
        echo "sonar.projectKey=$SONAR_PROJECTKEY" >> sonar-project.properties
        echo "sonar.projectName=$GITHUB_REPOSITORY" >> sonar-project.properties
        echo "sonar.sources=$GITHUB_WORKSPACE" >> sonar-project.properties
        echo "sonar.cfamily.build-wrapper-output=${GITHUB_WORKSPACE}/build" >> sonar-project.properties
        echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
    - name: build sonarqube
      run: |
        mkdir build
        cmake -S . -B build
        build-wrapper-linux-x86-64 --out-dir ${GITHUB_WORKSPACE}/build cmake --build build/ --config Release
    - name: scanner start
      run: sonar-scanner
