on:
  push:
    branches:
      - "sonarscan"
    paths:
      - ".github/workflows/sonar.yml"
jobs:
  call-workflow-1-in-local-repo:
    uses: /GitHub_CI/blob/main/templates/sonaver_cfamly.yml@main
    with:
      SONAR_PROJECTKEY: test
