on:
  push:
    branches:
      - "sonarscan"
    paths:
      - ".github/workflows/sonar.yml"

name: SonarQube
env:
  SONAR_PROJECTKEY: cFamily
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.7
      SONAR_SERVER_URL: ${{ secrets.SONAR_URL }}
      BUILD_WRAPPER_OUT_DIR: sonar_build
      SONAR_PROJECTKEY: cFamily
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download and set up sonar-scanner
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
        run: |
          mkdir -p $HOME/sonar
          curl -sSLo $HOME/sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }} 
          unzip -o $HOME/sonar/sonar-scanner.zip -d $HOME/sonar/
          echo "$HOME/sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux/bin" >> $GITHUB_PATH
      - name: Download and set up build-wrapper
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-linux-x86.zip
        run: |
          curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH
      - name: create property file
        run: |
          echo "sonar.host.url=${{ secrets.SONAR_URL }}" >> sonar-project.properties
          echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-project.properties
          echo "sonar.projectKey=$SONAR_PROJECTKEY" >> sonar-project.properties
          echo "sonar.projectName=$GITHUB_REPOSITORY" >> sonar-project.properties
          echo "sonar.sources=$GITHUB_WORKSPACE" >> sonar-project.properties
          echo "sonar.cfamily.build-wrapper-output=${GITHUB_WORKSPACE}/build" >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties 
      - name: Run build-wrapper
        run: |
          mkdir ${{ env.BUILD_WRAPPER_OUT_DIR }}
          cmake -S . -B ${{ env.BUILD_WRAPPER_OUT_DIR }}
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Release
      - name: Run sonar-scanner
        run: sonar-scanner
